Init home work1
wolfram12345/scala-school pull request #1
Opened 2017-03-11 16:55 UTC by wolfram12345

pullRequest1

2017-03-12 07:06 UTC, vatt2001 requested changes

2017-03-12 07:06 UTC, vatt2001 commented on src/main/scala/lectures/functions/Computations.scala
> +    (dataArray: Array[String]) => dataArray.filter(item => arrayFilterData.contains(item))
Sleep-ы надо вернуть, они нам потребуются в следующих заданиях.

2017-03-12 07:06 UTC, vatt2001 commented on src/main/scala/lectures/functions/Fibonacci.scala
> +    fibs(num - 1) + fibs(num - 2)
Лучше через else, так как в scala return-ы не поощряются и практически никогда не используются.

2017-03-12 07:06 UTC, vatt2001 commented on src/main/scala/lectures/functions/SQLAPI.scala
> +  private def logParameter[T](prm: T): T  = {   //Возможно, я неправильно понял логирование
Здесь все верно

2017-03-12 07:06 UTC, vatt2001 commented on src/main/scala/lectures/functions/SQLAPI.scala
> +  }
Это императивное решение, нам же нужно функциональное (т.е. через композицию функций при помощи `compose` и `andThen`). Посмотри примеры в слайдах лекции.

2017-03-13 09:36 UTC, sergeypopov83 commented on src/main/scala/lectures/functions/Fibonacci.scala
> +    if(num == 0)
В твоей реализации, если аккумулятор уже содержит num, мы все равно идем вычислять предыдущие числа.
Поменяй немного реализацию так. что бы лишних вычислени не было.

2017-03-13 22:23 UTC, vatt2001 requested changes

2017-03-13 22:23 UTC, vatt2001 commented on src/main/scala/lectures/functions/Computations.scala
> +    Thread.sleep(100)
Этот `sleep` эмулирует задержку вычисления `dataArray.filter(item => arrayFilterData.contains(item))` и должен выполняться вместе с этим выражением, т.е. должен быть внутри возвращаемой функции.

2017-03-13 22:23 UTC, vatt2001 commented on src/main/scala/lectures/functions/SQLAPI.scala
> +*/
Лишний закомментированный код надо убрать, он только мешает.

2017-03-14 22:54 UTC, merged