Home work3
wolfram12345/scala-school pull request #3
Opened 2017-04-02 07:59 UTC by wolfram12345

2017-04-02 19:30 UTC, vatt2001 requested changes

2017-04-02 19:30 UTC, vatt2001 commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +    var rightSeq = data.takeRight(lengthRightSeq)
посмотри на метод `data.splitAt`

2017-04-02 19:30 UTC, vatt2001 commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +    var rightSeq = data.takeRight(lengthRightSeq)
Попробуй написать без `var`, только `val`-ы

2017-04-02 19:30 UTC, vatt2001 commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +    for(i <- data.indices) yield{
Слияние лучше вынести в отдельный метод.
Попробуй написать его без ручного итерирования, с применением иммутабельных списков и pattern matching.

2017-04-02 19:30 UTC, vatt2001 commented on src/main/scala/lectures/collections/MyListImpl.scala
> +    def filter(f: (Int => Boolean)) = flatMap(t =>{
Значимый код в объявлении методов после `=` не стоит писать, лучше переносить на следующую строку, иначе он выпадает из поля зрения. Исключение - `argument match {`

2017-04-02 19:30 UTC, vatt2001 commented on src/main/scala/lectures/collections/MyListImpl.scala
> +        getValue(data, acc, f)
Лучше вместо вспомогательной функции вырази значение через рекурсивный вызов `MyList(...).foldLeft(...)`
Кстати, когда делаешь вспомогательные методы, надо делать их приватными и, по возможности, называть понятными именами (`getValue` явно имеет другой смысл)

2017-04-02 19:30 UTC, vatt2001 commented on src/main/scala/lectures/collections/OptionVsNPE.scala
> +      res
Попробуй написать в функциональном стиле, с применением `Option.apply` и `getOrElse`

2017-04-02 19:30 UTC, vatt2001 commented on src/main/scala/lectures/collections/OptionVsNPE.scala
> +      throw new ResourceException
Аналогично, `getOrElse`

2017-04-02 19:30 UTC, vatt2001 commented on src/main/scala/lectures/collections/OptionVsNPE.scala
> +    while ((connection = ConnectionProducer.produce(resource)) == null){}
Вместо цикла лучше сделать рекурсию. Заодно уйдёт и `var`

2017-04-02 19:30 UTC, vatt2001 commented on src/main/scala/lectures/collections/comprehension/Couriers.scala
> +    listServedAddresses.map(address => println(address.postIndex))
Когда мы для каждого элемента коллекции выполняем побочный эффект, то правильней использовать `foreach` вместо `map`. Это особенно важно для коллекций с ленивой генерацией (без явного вызова `force` у них ничего не будет выполняться).

2017-04-02 19:30 UTC, vatt2001 commented on src/main/scala/lectures/collections/comprehension/Couriers.scala
> +//    }
Нет смысла оставлять закомменченный код, когда у тебя есть система контроля версий

2017-04-02 19:30 UTC, vatt2001 commented on src/main/scala/lectures/collections/comprehension/Couriers.scala
> +case class accum(courier: Courier, indexCanServe: Int, servedAddresses: List[Address])
Имя кейс-классов надо писать с большой буквы

2017-04-02 19:30 UTC, vatt2001 commented on src/main/scala/lectures/collections/comprehension/Couriers.scala
> +    addresses.foldLeft(nullAccum)((acc, address) =>{
Ты познал и попрактиковался со сложным обходом списка в функциональном стиле.
Однако, здесь можно всё сделать гораздо проще.
Обрати внимание на тот факт, что для ответа на задачу тебе не важно знать, какой именно курьер обслужил какой адрес. Тебе важно лишь общее число обслуженных адресов.

2017-04-02 19:30 UTC, vatt2001 commented on src/main/scala/lectures/collections/comprehension/Couriers.scala
> +      null
Использовать `null`-ы, когда у тебя есть `Option`-ы - грешно :)

2017-04-02 19:30 UTC, vatt2001 commented on src/main/scala/lectures/collections/comprehension/Couriers.scala
> +      if(courier == null){
От многоэтажных if-ов хорошо спасает pattern matching

2017-04-02 19:30 UTC, vatt2001 commented on src/main/scala/lectures/collections/comprehension/Couriers.scala
> +  def getCourier(iterator: Iterator[Courier]): Courier = {
А этот метод, фактически, является `Stream`-ами (очень похоже на концепцию генераторов, про которые я рассказывал в юнит-тестировании)

2017-04-07 17:22 UTC, wolfram12345 commented on src/main/scala/lectures/collections/comprehension/Couriers.scala
> +//    }
Мне нужно видеть код из задания одновременно со своим.

2017-04-07 17:23 UTC, wolfram12345 commented on src/main/scala/lectures/collections/MyListImpl.scala
> +    def filter(f: (Int => Boolean)) = flatMap(t =>{
Вот тут не понял. Можно чуть подробнее?

2017-04-07 17:24 UTC, wolfram12345 commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +    var rightSeq = data.takeRight(lengthRightSeq)
Почему мы отказываемся от var и mutable коллекций? Они, обычно, удобнее....

2017-04-09 12:52 UTC, vatt2001 requested changes

2017-04-09 12:52 UTC, vatt2001 commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +        case headData2 :: tailData2 => merge(Nil, tailData2, outputData :+ headData2)
В случае, когда у тебя один из списков закончился, нет смысла бежать по другому списку по одному элементу, можно вернуть сразу конкатенацию того, что осталось, с результатом.

2017-04-09 12:52 UTC, vatt2001 commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +        case headData2 :: tailData2 => merge(Nil, tailData2, outputData :+ headData2)
А вообще - наглядней так:

```
(data1.headOption, data2.headOption) match {
  case (Some(a), Some(b)) if a >= b => // ...
  case (Some(a), Some(b)) if a < b => // ...
  case (Some(a), None) => // ...
  case (None, Some(b)) => // ...
  case (None, None) => // ...
}
```

2017-04-09 12:52 UTC, vatt2001 commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +    val rightSeq = if(separatedLists._2.length > 1) mergeSort(separatedLists._2) else separatedLists._2
Зачем эти доп.проверки?

2017-04-09 12:52 UTC, vatt2001 commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +    val separatedLists = data.splitAt(separateLength)
`val (left, right) = data.splitAt(data.length / 2)`

2017-04-09 12:52 UTC, vatt2001 commented on src/main/scala/lectures/collections/comprehension/Couriers.scala
> +//    }
Да, но в итоговую кодовую базу закомменченный код попадать не должен.
Надо сравнить - используй инструменты системы контроля версий (в т.ч. Идея это умеет)

2017-04-14 14:08 UTC, wolfram12345 commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +    val rightSeq = if(separatedLists._2.length > 1) mergeSort(separatedLists._2) else separatedLists._2
Чтобы остановить рекурсивное погружение. Ведь если длина Seq равна единице, то дальше вызывать mergeSort смысла нет?

2017-04-14 14:08 UTC, wolfram12345 commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +    val rightSeq = if(separatedLists._2.length > 1) mergeSort(separatedLists._2) else separatedLists._2
Чтобы остановить рекурсивное погружение. Ведь если длина Seq равна единице, то дальше вызывать mergeSort смысла нет?

2017-04-15 08:53 UTC, vatt2001 commented on src/main/scala/lectures/collections/MyListImpl.scala
> +    def filter(f: (Int => Boolean)) = flatMap(t =>{
Вот это:
```
def filter(f: (Int => Boolean)) = {
  flatMap(t =>{
```
лучше, чем это:
```
def filter(f: (Int => Boolean)) = flatMap(t =>{
```

2017-04-15 08:57 UTC, vatt2001 commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +    var rightSeq = data.takeRight(lengthRightSeq)
Они несут дополнительную сложность при анализе возможных сайд-эффектов.
Когда у тебя переменная объявлена как val, а значение иммутабельное, то ты точно знаешь, что там ничего никогда не поменяется. И еще очень важное свойство - эту переменную можно запросто использовать в многопоточных методах.

var и mutable кажутся удобней только когда ты еще не научился нормально писать в функциональном стиле.

2017-04-15 08:59 UTC, vatt2001 commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +    val rightSeq = if(separatedLists._2.length > 1) mergeSort(separatedLists._2) else separatedLists._2
С чисто алгоритмической точки зрения выглядит как микрооптимизация (не сильно обоснованная). С практической точки зрения это больше затрудняет чтение кода, чем дает профита (имхо).
Конечно, если в будущем этот кусок кода будет высоконагружен и именно здесь будет узкое место, тогда да, это будет обоснованно. Но не сейчас.

2017-04-15 09:02 UTC, vatt2001 approved these changes

2017-04-15 09:02 UTC, vatt2001 commented on src/main/scala/lectures/collections/comprehension/Couriers.scala
> +    addresses.take(countAddresses)
`val countAddresses = couriers.filter(_ => traffic().degree < 5).map(_.canServe).sum`

2017-04-15 09:02 UTC, merged